import { createContext, useContext, useEffect, useState } from "react";

const translations = {
  fr: {
    home: "Accueil",
    learn: "Apprendre",
    tutor: "Tuteur IA",
    contribute: "Contribuer",
    progress: "Progrès",
    review: "Révision",
    account: "Mon espace",
    personalSpace: "Espace personnel",
    signedIn: "Compte connecté",
    dashboard: "Tableau de bord",
    settings: "Réglages, Paramètres & Confidentialité",
    profile: "Profil",
    support: "Centre d'aide / Support",
    administration: "Administration / Admin",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    logout: "Déconnexion",
    login: "Connexion",
    welcome: "Bienvenue sur Mǎa-kwɛ́lî Langues",
    welcomeText: "Poursuivez votre apprentissage à votre rythme et développez une maîtrise durable des langues qui vous ouvrent au monde.",
    continueLearning: "Continuer mon apprentissage",
    startNow: "Commencer maintenant",
    activeLanguages: "langues actives",
    yourPaths: "Vos parcours",
    resume: "Reprenez là où vous en êtes",
    seeAll: "Voir tout",
    lessonOf: (lesson, total) => `Leçon ${lesson} sur ${total}`,
    discover: "À découvrir",
    discoverPaths: "Des parcours qui donnent envie de commencer",
    explore: "Explorer",
    quickActions: "Actions rapides",
    directAccess: "Accédez directement à ce qui compte",
    workshop: "Espace créatif",
    workshopText: "Pratiquez, enregistrez et perfectionnez votre expression.",
    language: "Langue",
    welcomeBack: "Bon retour parmi nous",
    createAccount: "Créer votre compte",
    signIn: "Se connecter",
    signUp: "Créer un compte",
    signUpNow: "Créer mon compte",
    newHere: "Nouveau ici ?",
    alreadyAccount: "Déjà un compte ?",
    authSubtitle: "Accédez à vos leçons, progrès et contenus préférés en un instant.",
    authSignupSubtitle: "Rejoignez Mǎa-kwɛ́lî Langues et débloquez un apprentissage plus vivant.",
    continueGoogle: "Continuer avec Google",
    or: "ou",
    fullName: "Nom complet",
    yourName: "Votre nom",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    passwordRequirements: "12 caractères minimum, avec une majuscule, une minuscule, un chiffre et un caractère spécial.",
    rememberMe: "Se souvenir de moi",
    forgotPassword: "Mot de passe oublié ?",
    hide: "Masquer",
    show: "Voir",
    secureLogin: "Connexion sécurisée · Vos données restent privées",
    signingIn: "Connexion en cours...",
    creating: "Création...",
    learnDifferently: "Apprends autrement",
    welcomeTo: "Bienvenue chez Mǎa-kwɛ́lî",
    buildPath: "Construisez votre parcours de langues avec des contenus immersifs et des activités guidées.",
    readySpace: "Votre espace d’apprentissage est prêt. Connectez-vous pour reprendre là où vous vous êtes arrêté.",
    secureData: "Connexion sécurisée · Vos données restent privées",
    notYetAccount: "Pas encore de compte ?",
    resendVerification: "Renvoyer l'e-mail de vérification",
    sending: "Envoi...",
    verificationSent: "Un nouvel e-mail de vérification a été envoyé.",
    enterEmailAgain: "Veuillez saisir votre adresse e-mail et réessayer.",
    googleVerification: "Votre adresse e-mail Google doit être confirmée avant d'accéder à l'application. Consultez votre boîte mail.",
    passwordShort: "Le mot de passe doit contenir au moins 12 caractères.",
    emailRequired: "Email et mot de passe sont requis.",
    invalidEmail: "Veuillez saisir une adresse e-mail valide.",
    verificationRequired: "Votre adresse e-mail doit être vérifiée avant de vous connecter. Un lien de confirmation vient d'être envoyé dans votre boîte mail.",
    invalidLogin: "Adresse e-mail ou mot de passe incorrect.",
    verificationQuestion: "Vous n'avez pas reçu l'e-mail de vérification ?",
    resetPasswordTitle: "Nouveau mot de passe",
    newPassword: "Nouveau mot de passe",
    resetPasswordAction: "Réinitialiser",
    resetPasswordSaving: "Enregistrement...",
    passwordMismatch: "Les mots de passe ne correspondent pas",
    resetTokenMissing: "Jeton de réinitialisation introuvable",
    resetPasswordError: "Erreur lors de la réinitialisation",
    "Aucune modification à enregistrer.": "Aucune modification à enregistrer.",
    "Remplissez les trois champs du changement de mot de passe.": "Remplissez les trois champs du changement de mot de passe.",
    "Les nouveaux mots de passe ne correspondent pas.": "Les nouveaux mots de passe ne correspondent pas.",
    "Le nouveau mot de passe doit contenir 12 caractères, une majuscule, une minuscule, un chiffre et un caractère spécial.": "Le nouveau mot de passe doit contenir 12 caractères, une majuscule, une minuscule, un chiffre et un caractère spécial.",
    "Profil et sécurité mis à jour.": "Profil et sécurité mis à jour.",
    "Impossible de mettre à jour le profil.": "Impossible de mettre à jour le profil.",
    "Enregistrement...": "Enregistrement...",
    "Enregistrer les modifications": "Enregistrer les modifications",
    personalDashboard: "Tableau de bord personnel",
    myProgress: "Ma progression",
    progressDescription: "Suivez vos progrès et reprenez vos parcours en un coup d’œil.",
    currentRank: "Rang actuel",
    still: "Encore",
    totalLessons: "leçons totales",
    to: "jusqu’à",
    maxLevelReached: "Niveau maximum atteint",
    beginner: "Débutant",
    learner: "Apprenti",
    intermediate: "Intermédiaire",
    advanced: "Avancé",
    loadingProgress: "Chargement de la progression...",
    noProgressYet: "Aucune progression pour le moment",
    startLearningToSeeProgress: "Commencez à apprendre une langue pour voir votre progression ici",
    progressionByLanguage: "Progression par langue",
    lessonsMastered: "Leçons maîtrisées",
    maxStreakDays: "Série max (j)",
    languagesActive: "langues actives",
    exploreLanguages: "Explorer les langues",
    pathsInProgress: "Parcours en cours",
    resumeWhereStopped: "Continuez là où vous vous êtes arrêté.",
    discoverTitle: "À découvrir",
    startNewPath: "Commencez un nouveau parcours.",
    notStartedYet: "Pas encore commencé",
    startNowAction: "Commencer",
    activeMemorization: "Mémorisation active",
    reviewIntelligently: "Réviser intelligemment",
    spacedReviewDescription: "Des rappels adaptés à votre mémoire grâce à la répétition espacée.",
    offlineReview: "Mode hors-ligne — révision des leçons téléchargées",
    addWordToReview: "Ajouter un mot à réviser",
    afterSubmission: "Après l’envoi :",
    newConversation: "Nouvelle conversation",
    aiCoach: "Tuteur IA",
    languageActive: "Langue active",
    online: "En ligne",
    voice: "Voix",
    modeSiri: "Mode Siri",
    stop: "Stop",
    focusTitle: "Focus",
    suggestionsTitle: "Suggestions",
    progressToday: "Progression du jour",
    messageCount: (count) => count > 1 ? "messages" : "message",
    languageCoach: "Coach de langue",
    helloKoro: "Bonjour ! Je suis Kôrô",
    koroIntro: "Ton assistant IA pour apprendre les langues africaines et internationales. Pose-moi une question, ou active le Mode Siri pour parler naturellement.",
    listen: "Écouter",
    assistantLabel: "Kôrô",
    userLabel: "Vous",
    thinking: "Je réfléchis",
    readyToListen: "Prêt à écouter",
    askLanguageQuestion: "Posez votre question...",
    listening: "Écoute...",
    audioListen: "Écouter",
    pronunciation: "Prononciation",
    conversation: "Conversation",
    culture: "Culture",
    translation: "Traduction",
    context: "Contexte",
    dictionary: "Dictionnaire",
    siriActivated: "Mode Siri activé. Parlez naturellement.",
    siriActivatedVoice: "Mode Siri activé. Je vous écoute.",
    micUnsupported: "La reconnaissance vocale n’est pas prise en charge par ce navigateur.",
    unknownError: "Erreur inconnue",
    tutorError: "Désolé, je n’ai pas pu répondre.",
    assistantDescription: "Assistant IA Mǎa-kwɛ́lî",
    languagesCount: "langues",
    wordsCount: "mots",
    accent: "Accent",
    ipaTones: "IPA + tons",
    historicalUses: "Historique et usages",
    adaptedAccent: "Adapté à l’accent",
    contributeTitle: "Contribuer à une langue",
    contributeSubtitle: "Enregistre ta voix, ajoute des mots et phonétiques pour ta langue.",
    contributeCalloutTitle: "Partage ta langue",
    contributeCalloutText: "Chaque contribution est vérifiée avant publication.",
    languageConcerned: "Langue concernée",
    languageConcernedHint: "Sélectionnez la langue du mot ou de l’expression.",
    selectLanguagePlaceholder: "Sélectionner une langue...",
    recordingStudio: "Studio d’enregistrement",
    recordingInProgress: "Enregistrement en cours",
    clickToRecord: "Cliquez pour enregistrer",
    stopRecording: "Clique sur le carré pour arrêter",
    microphoneUnsupported: "Ton navigateur ne supporte pas l'enregistrement.",
    microphoneAccess: "Autorisez l'accès au micro dans ton navigateur.",
    recordingReady: "Enregistrement prêt",
    reRecord: "Réenregistrer",
    deleteText: "Supprimer",
    speakerProfile: "Profil du locuteur",
    requiredFields: "Les champs marqués d’un astérisque sont obligatoires.",
    wordExpression: "Mot ou expression",
    phoneticLabel: "Phonétique (IPA ou simple)",
    translationFrench: "Traduction française",
    speakerProfileText: "Ces informations nous aident à documenter la contribution.",
    firstName: "Prénom",
    region: "Région",
    notesContext: "Notes et contexte",
    optional: "facultatif",
    fillRequiredFields: "Veuillez remplir tous les champs obligatoires.",
    sendingContribution: "Envoi...",
    submitContribution: "Envoyer la contribution",
    contributionSubmitted: "Contribution soumise !",
    contributeAfterReview: "Chaque contribution est vérifiée avant publication.",
    "My badges": "Mes badges",
    "My contributions": "Mes contributions",
    "Settings and privacy": "Réglages et confidentialité",
    "Settings sections": "Sections des réglages",
    "Settings": "Réglages",
    "Account Information": "Informations du compte",
    "Update your name and password.": "Modifiez votre nom et votre mot de passe.",
    "Username": "Nom d'utilisateur",
    "Current password": "Mot de passe actuel",
    "New password": "Nouveau mot de passe",
    "Confirm new password": "Confirmer le nouveau mot de passe",
    "The new password must contain 12 characters, an uppercase letter, a lowercase letter, a number, and a special character.": "Le nouveau mot de passe doit contenir 12 caractères, une majuscule, une minuscule, un chiffre et un caractère spécial.",
    "Open my profile": "Ouvrir mon profil",
    "Manage now": "Gérer maintenant",
    "Account": "Compte",
    "Security": "Sécurité",
    "Notifications": "Notifications",
    "My account": "Mon compte",
    "Security & privacy": "Sécurité et confidentialité",
    "Manage your profile, preferences, and personal information.": "Gérez votre profil, vos préférences et vos informations personnelles.",
    "Enable an extra layer of protection for your account.": "Activez une couche de protection supplémentaire pour votre compte.",
    "Control alerts and learning reminders.": "Contrôlez les alertes et les rappels d'apprentissage.",
  },
  en: {
    home: "Home",
    learn: "Learn",
    tutor: "AI Tutor",
    contribute: "Contribute",
    progress: "Progress",
    review: "Review",
    account: "My space",
    personalSpace: "Personal space",
    signedIn: "Signed-in account",
    dashboard: "Dashboard",
    settings: "Settings & Privacy",
    profile: "Profile",
    support: "Help & Support",
    administration: "Administration",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    logout: "Sign out",
    login: "Sign in",
    welcome: "Welcome to Mǎa-kwɛ́lî Langues",
    welcomeText: "Continue learning at your own pace and build lasting mastery of the languages that open the world to you.",
    continueLearning: "Continue learning",
    startNow: "Get started",
    activeLanguages: "active languages",
    yourPaths: "Your learning paths",
    resume: "Pick up where you left off",
    seeAll: "See all",
    lessonOf: (lesson, total) => `Lesson ${lesson} of ${total}`,
    discover: "Discover",
    discoverPaths: "Learning paths worth starting",
    explore: "Explore",
    quickActions: "Quick actions",
    directAccess: "Go straight to what matters",
    workshop: "Creative studio",
    workshopText: "Practice, record, and refine your expression.",
    language: "Language",
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    signIn: "Sign in",
    signUp: "Create an account",
    signUpNow: "Create my account",
    newHere: "New here?",
    alreadyAccount: "Already have an account?",
    authSubtitle: "Access your lessons, progress, and favorite content in an instant.",
    authSignupSubtitle: "Join Mǎa-kwɛ́lî Langues and unlock a more engaging learning experience.",
    continueGoogle: "Continue with Google",
    or: "or",
    fullName: "Full name",
    yourName: "Your name",
    password: "Password",
    confirmPassword: "Confirm password",
    passwordRequirements: "At least 12 characters, including an uppercase letter, a lowercase letter, a number, and a special character.",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    hide: "Hide",
    show: "Show",
    secureLogin: "Secure sign-in · Your data stays private",
    signingIn: "Signing in...",
    creating: "Creating...",
    learnDifferently: "Learn differently",
    welcomeTo: "Welcome to Mǎa-kwɛ́lî",
    buildPath: "Build your language journey with immersive content and guided activities.",
    readySpace: "Your learning space is ready. Sign in to pick up where you left off.",
    secureData: "Secure sign-in · Your data stays private",
    notYetAccount: "Don't have an account yet?",
    resendVerification: "Resend verification email",
    sending: "Sending...",
    verificationSent: "A new verification email has been sent.",
    enterEmailAgain: "Enter your email address and try again.",
    googleVerification: "Your Google email address must be verified before you can access the application. Check your inbox.",
    passwordShort: "Your password must contain at least 12 characters.",
    emailRequired: "Email and password are required.",
    invalidEmail: "Please enter a valid email address.",
    verificationRequired: "Your email address must be verified before signing in. A confirmation link has been sent to your inbox.",
    invalidLogin: "Incorrect email address or password.",
    verificationQuestion: "Didn't receive the verification email?",
    emailSent: "Email sent!",
    resetPasswordTitle: "Forgot password",
    resetPasswordSubtitle: "Enter your email address to receive a reset link.",
    backToLogin: "Back to sign in",
    sendResetLink: "Send reset link",
    emailVerificationTitle: "Email verification",
    emailVerificationMissing: "Verification link missing.",
    emailVerificationSuccess: "Email verified. Signing you in...",
    emailVerificationInvalid: "Verification link invalid or expired.",
    goToLogin: "Go to sign in",
    verificationInProgress: "Verifying...",
    passwordMismatch: "Passwords do not match.",
    emailAddressRequired: "Please enter an email address.",
    registrationError: "Error during registration.",
    registrationSuccess: "Account created. Please check your inbox and click the verification link before signing in.",
    registrationAlreadyVerified: "Account created. Your email is already verified, so you can sign in immediately.",
    emailAlreadyUsed: "This email address is already in use. Sign in with this account or reset your password.",
    verificationRateLimit: "Too many confirmation emails have been sent. Please wait a few minutes, then try again with the same email address or use the resend option from the sign-in page.",
    verificationResendInfo: "Check your inbox to confirm:",
    resendVerificationLink: "Resend verification email",
    goToLoginAlt: "Go to sign in",
    resetPasswordAlt: "Reset password",
    supportHelpCenterTitle: "Help center",
    supportHelpCenterDescription: "Check quick tips and application documentation.",
    supportHelpCenterAction: "View FAQs",
    supportHelpCenterDetails: "Start by checking your login reminders, API access, and privacy settings to resolve common issues.",
    supportTitle: "Support",
    supportDescription: "Contact the team for personalized assistance.",
    supportAction: "Contact support",
    supportDetails: "Send a message to the support team for a specific issue, bug, or profile request.",
    supportFeedbackTitle: "Feedback",
    supportFeedbackDescription: "Share your ideas to improve the learning experience.",
    supportFeedbackAction: "Share feedback",
    supportFeedbackDetails: "Your feedback helps prioritize improvements to navigation, content, and progress.",
    supportFaqTitle: "Frequently asked questions",
    supportFaqDescription: "Answers to the most common situations.",
    supportSearchPlaceholder: "Search help...",
    supportNoResults: "No answer found.",
    supportAssistant: "Support assistant",
    supportOnline: "Services online",
    supportOffline: "Offline mode",
    supportContactEmail: "Copy email address",
    supportCopyDone: "Address copied",
    supportCopyFailed: "Copy failed",
    supportOpenSettings: "Open settings",
    supportBackHome: "Back to home",
    supportEmailSubject: "Mǎa-kwɛ́lî support request",
    supportEmailBody: "Hello,\n\nI would like to contact you regarding:\n- \n\nAdditional information:\n",
    supportFeedbackSubject: "Mǎa-kwɛ́lî feedback",
    supportFaq1Question: "I can't sign in",
    supportFaq1Answer: "Check your email address and password. If your email is not verified, use the resend link shown on the sign-in page.",
    supportFaq2Question: "How do I resume a lesson?",
    supportFaq2Answer: "Open Learn, select a language, and choose a lesson. Your progress is saved automatically after each activity.",
    supportFaq3Question: "How do I use offline mode?",
    supportFaq3Answer: "From a language path, use Download for offline use while connected. Downloaded content remains available without internet access.",
    supportFaq4Question: "How do I submit a contribution?",
    supportFaq4Answer: "In Contribute, select the language, enter the word and its translation, then add a note or audio recording before submitting.",
    supportFaq5Question: "When will my contribution be published?",
    supportFaq5Answer: "Each contribution is reviewed by the team before publication. You can follow its status from your profile.",
    supportQuestionsPrompt: "Questions, ideas, or issues?",
    navKoroAI: "Kôrô, AI tutor",
    personalDashboard: "Personal dashboard",
    myProgress: "My progress",
    progressDescription: "Track your progress and resume your learning paths at a glance.",
    currentRank: "Current rank",
    still: "Still",
    totalLessons: "total lessons",
    to: "to",
    maxLevelReached: "Maximum level reached",
    beginner: "Beginner",
    learner: "Learner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    loadingProgress: "Loading progress...",
    noProgressYet: "No progress yet",
    startLearningToSeeProgress: "Start learning a language to see your progress here",
    progressionByLanguage: "Progression by language",
    lessonsMastered: "Lessons mastered",
    maxStreakDays: "Max streak (days)",
    languagesActive: "active languages",
    exploreLanguages: "Explore languages",
    pathsInProgress: "Paths in progress",
    resumeWhereStopped: "Continue where you left off.",
    discoverTitle: "Discover",
    startNewPath: "Start a new learning path.",
    notStartedYet: "Not started yet",
    startNowAction: "Start",
    activeMemorization: "Active memorization",
    reviewIntelligently: "Review intelligently",
    spacedReviewDescription: "Memory-friendly recall reminders powered by spaced repetition.",
    offlineReview: "Offline mode — review downloaded lessons",
    addWordToReview: "Add a word to review",
    afterSubmission: "After sending:",
    newConversation: "New conversation",
    aiCoach: "AI tutor",
    languageActive: "Active language",
    online: "Online",
    voice: "Voice",
    modeSiri: "Siri mode",
    stop: "Stop",
    focusTitle: "Focus",
    suggestionsTitle: "Suggestions",
    progressToday: "Today's progress",
    messageCount: (count) => count > 1 ? "messages" : "message",
    languageCoach: "Language coach",
    helloKoro: "Hello! I'm Kôrô",
    koroIntro: "Your AI assistant for learning African and international languages. Ask me a question, or turn on Siri mode to speak naturally.",
    listen: "Listen",
    assistantLabel: "Kôrô",
    userLabel: "You",
    thinking: "Thinking",
    readyToListen: "Ready to listen",
    askLanguageQuestion: "Ask your question...",
    listening: "Listening...",
    audioListen: "Listen",
    pronunciation: "Pronunciation",
    conversation: "Conversation",
    culture: "Culture",
    translation: "Translation",
    context: "Context",
    dictionary: "Dictionary",
    siriActivated: "Siri mode activated. Speak naturally.",
    siriActivatedVoice: "Siri mode activated. I’m listening.",
    micUnsupported: "Speech recognition is not supported by this browser.",
    unknownError: "Unknown error",
    tutorError: "Sorry, I couldn’t answer.",
    assistantDescription: "Mǎa-kwɛ́lî AI assistant",
    languagesCount: "languages",
    wordsCount: "words",
    accent: "Accent",
    ipaTones: "IPA + tones",
    historicalUses: "History and usage",
    adaptedAccent: "Accent-aware",
    contributeTitle: "Contribute to a language",
    contributeSubtitle: "Record your voice and add words and phonetics for your language.",
    contributeCalloutTitle: "Share your language",
    contributeCalloutText: "Every contribution is reviewed before publication.",
    languageConcerned: "Language concerned",
    languageConcernedHint: "Select the language of the word or expression.",
    selectLanguagePlaceholder: "Select a language...",
    recordingStudio: "Recording studio",
    recordingInProgress: "Recording in progress",
    clickToRecord: "Click to record",
    stopRecording: "Click the square to stop",
    microphoneUnsupported: "Your browser does not support recording.",
    microphoneAccess: "Allow microphone access in your browser.",
    recordingReady: "Recording ready",
    reRecord: "Record again",
    deleteText: "Delete",
    speakerProfile: "Speaker profile",
    requiredFields: "Fields marked with an asterisk are required.",
    wordExpression: "Word or expression",
    phoneticLabel: "Phonetics (IPA or simple)",
    translationFrench: "French translation",
    speakerProfileText: "This information helps us document the contribution.",
    firstName: "First name",
    region: "Region",
    notesContext: "Notes and context",
    optional: "optional",
    fillRequiredFields: "Please fill in all required fields.",
    sendingContribution: "Sending...",
    submitContribution: "Submit contribution",
    contributionSubmitted: "Contribution submitted!",
    contributeAfterReview: "Every contribution is reviewed before publication.",
    "jours série": "day streak",
    badgeBeginnerTitle: "First steps",
    badgeBeginnerDesc: "1 lesson completed",
    badgeDiligentTitle: "Diligent",
    badgeDiligentDesc: "10 lessons",
    badgeExpertTitle: "Expert",
    badgeExpertDesc: "30 lessons",
    badgePolyglotTitle: "Polyglot",
    badgePolyglotDesc: "3 languages",
    badgeRegularTitle: "Regular",
    badgeRegularDesc: "7 day streak",
    badgeXPHunterTitle: "XP Hunter",
    badgeXPHunterDesc: "500 XP",
    badgeContributorTitle: "Contributor",
    badgeContributorDesc: "1 contribution",
    badgeBenefactorTitle: "Benefactor",
    badgeBenefactorDesc: "5 contributions",
    "My badges": "My badges",
    "My contributions": "My contributions",
    "Settings and privacy": "Settings and privacy",
    "Settings sections": "Settings sections",
    "Settings": "Settings",
    "Account Information": "Account Information",
    "Update your name and password.": "Update your name and password.",
    "Username": "Username",
    "Current password": "Current password",
    "New password": "New password",
    "Confirm new password": "Confirm new password",
    "The new password must contain 12 characters, an uppercase letter, a lowercase letter, a number, and a special character.": "The new password must contain 12 characters, an uppercase letter, a lowercase letter, a number, and a special character.",
    newPassword: "New password",
    resetPasswordAction: "Reset",
    resetPasswordSaving: "Saving...",
    resetTokenMissing: "Reset token not found.",
    resetPasswordError: "Error while resetting the password.",
    "Aucune modification à enregistrer.": "No changes to save.",
    "Remplissez les trois champs du changement de mot de passe.": "Please fill in all three password fields.",
    "Les nouveaux mots de passe ne correspondent pas.": "The new passwords do not match.",
    "Le nouveau mot de passe doit contenir 12 caractères, une majuscule, une minuscule, un chiffre et un caractère spécial.": "The new password must contain 12 characters, an uppercase letter, a lowercase letter, a number, and a special character.",
    "Profil et sécurité mis à jour.": "Profile and security updated.",
    "Impossible de mettre à jour le profil.": "Unable to update the profile.",
    "Enregistrement...": "Saving...",
    "Enregistrer les modifications": "Save changes",
  },
};

const sharedUiTranslations = {

  "Chargement...": "Loading...",
  "Erreur: ": "Error: ",
  "Apprentissage des langues": "Language learning",
  "Toutes les langues": "All languages",
  "Rechercher une langue...": "Search for a language...",
  "Aucun résultat": "No results",
  "Voir les leçons": "View lessons",
  "Continuer": "Continue",
  "Commencer": "Start",
  "Retour": "Back",
  "Fermer": "Close",
  "Valider": "Submit",
  "Annuler": "Cancel",
  "Supprimer": "Delete",
  "Modifier": "Edit",
  "Enregistrer les modifications": "Save changes",
  "Chargement des langues...": "Loading languages...",
  "Aucun parcours disponible.": "No learning path available.",
  "Leçon suivante": "Next lesson",
  "Leçon précédente": "Previous lesson",
  "Marquer comme terminée": "Mark as complete",
  "Leçon terminée": "Lesson completed",
  "Félicitations !": "Congratulations!",
  "Bien joué !": "Well done!",
  "Réessayer": "Try again",
  "Envoyer": "Send",
  "Envoi...": "Sending...",
  "Enregistrement...": "Saving...",
  "Sauvegarder": "Save",
  "Sauvegardé": "Saved",
  "Créer": "Create",
  "Créer la leçon": "Create lesson",
  "Créer le vocabulaire": "Create vocabulary",
  "Aucune donnée disponible.": "No data available.",
  "Aucun utilisateur trouvé.": "No users found.",
  "Aucune contribution trouvée.": "No contributions found.",
  "En attente de validation": "Awaiting approval",
  "Approuver": "Approve",
  "Rejeter": "Reject",
  "Mot": "Word",
  "Traduction": "Translation",
  "Prononciation": "Pronunciation",
  "Exemple": "Example",
  "Contexte": "Context",
  "Notes": "Notes",
  "Sélectionnez un fichier": "Select a file",
  "Choisir un fichier": "Choose a file",
  "Aucun fichier choisi": "No file chosen",
  "Le fichier est trop volumineux.": "The file is too large.",
  "Veuillez remplir tous les champs obligatoires.": "Please fill in all required fields.",
  "Contribution soumise !": "Contribution submitted!",
  "Microphone inaccessible : ": "Microphone unavailable: ",
  "Ton navigateur ne supporte pas l'enregistrement.": "Your browser does not support recording.",
  "Autorisez l'accès au micro dans ton navigateur.": "Allow microphone access in your browser.",
  "Sélectionnez un fichier image.": "Select an image file.",
  "L’image doit faire moins de 10 Mo.": "The image must be smaller than 10 MB.",
  "Impossible de préparer l’image pour l’analyse.": "Unable to prepare the image for analysis.",
  "Impossible de lire l’image pour l’analyse.": "Unable to read the image for analysis.",
  "Cette image reste trop volumineuse après compression. Choisissez une image plus légère.": "This image is still too large after compression. Choose a smaller image.",
  "Reconnaissance vocale non supportée. Utilisez Chrome ou Edge.": "Speech recognition is not supported. Use Chrome or Edge.",
  "Écoutez, enregistrez et comparez votre prononciation.": "Listen, record, and compare your pronunciation.",
  "Mot à prononcer": "Word to pronounce",
  "Analyser": "Analyze",
  "Analyse en cours...": "Analyzing...",
  "Votre prononciation": "Your pronunciation",
  "Score de similarité": "Similarity score",
  "Actualiser": "Refresh",
  "Classement": "Leaderboard",
  "Ma position": "My position",
  "Réinitialisation dans": "Resets in",
  "te séparent de": "separate you from",
  "Aucun classement disponible.": "No leaderboard available.",
  "Partager": "Share",
  "Copier": "Copy",
  "Copié !": "Copied!",
  "Une erreur est survenue.": "Something went wrong.",
  "Accès refusé": "Access denied",
  "Cette page est réservée aux administrateurs.": "This page is reserved for administrators.",
  "Retour à l'accueil": "Back to home",
  "Centre de contrôle": "Control center",
  "Gérer les langues, les leçons, les utilisateurs et les contenus assistés par IA.": "Manage languages, lessons, users, and AI-assisted content.",
  "Accès administrateur": "Administrator access",
  "Actualiser les données": "Refresh data",
  "Contribuer à une langue": "Contribute to a language",
  "Partagez un mot, une prononciation ou un usage local. Chaque contribution est vérifiée avant publication.": "Share a word, pronunciation, or local usage. Every contribution is reviewed before publication.",
  "Enregistre ta voix, ajoute des mots et phonétiques pour ta langue. Après validation, ta contribution enrichit l'application pour tous les apprenants.": "Record your voice and add words and phonetics for your language. Once approved, your contribution enriches the app for all learners.",
  "Langue concernée": "Language concerned",
  "Sélectionnez la langue du mot ou de l’expression.": "Select the language of the word or expression.",
  "Sélectionner une langue...": "Select a language...",
  "Clique sur le carré pour arrêter": "Click the square to stop",
  "Enregistrement prêt": "Recording ready",
  "Réenregistrer": "Record again",
  "Les champs marqués d’un astérisque sont obligatoires.": "Fields marked with an asterisk are required.",
  "Phonétique (IPA ou simple)": "Phonetics (IPA or simple)",
  "Accès restreint": "Restricted access",
  "Aucun exercice disponible pour cette leçon.": "No exercise is available for this lesson.",
  "Défi adaptatif": "Adaptive challenge",
  "Les exercices difficiles reviennent en priorité pour t’aider à progresser.": "Difficult exercises return first to help you improve.",
  "Progression du défi": "Challenge progress",
  "Dernière question, donne tout !": "Last question, give it your best!",
  "à revoir": "to review",
  "maîtrisés": "mastered",
  "Complète la réponse": "Complete the answer",
  "Rédige ta réponse courte": "Write your short answer",
  "Écrivez votre réponse ici…": "Write your answer here...",
  "Langue introuvable ou leçon invalide.": "Language not found or invalid lesson.",
  "Aucun mot trouvé pour cette leçon.": "No words found for this lesson.",
  "Module introuvable.": "Module not found.",
  "Voir la langue": "View language",
  "Question": "Question",
  "Mode hors-ligne": "Offline mode",
  "Téléchargement...": "Downloading...",
  "Retirer le téléchargement": "Remove download",
  "Télécharger pour hors-ligne": "Download for offline use",
  "Jour(s) série": "Day streak",
  "XP totaux": "Total XP",
  "Hors-ligne": "Offline",
  "Objectifs à débloquer": "Goals to unlock",
  "Focus phonétique": "Phonetics focus",
  "Le défi de la leçon": "Lesson challenge",
  "Sources de la leçon": "Lesson sources",
  "Apprentissage": "Learning",
  "Conversation": "Conversation",
  "Je suis": "I am",
  "À retenir": "Key points to remember",
  "Les sons clés": "Key sounds",
  "Point de vigilance": "Watch out",
  "Les erreurs à éviter": "Common mistakes to avoid",
  "Évaluation": "Assessment",
  "Lancer le défi": "Start the challenge",
  "Provenance": "Source",
  "Fiabilité": "Reliability",
  "Fichier de données": "Data file",
  "Note méthodologique": "Method note",
  "Repère": "Highlight",
  "Réduire l’explication": "Collapse explanation",
  "Ouvrir l’explication →": "Open explanation →",
  "Phrase": "Phrase",
  "Quelle est la traduction ?": "What is the translation?",
  "Commencer l’examen": "Start review",
  "Consigne": "Instruction",
  "Exercice": "Exercise",
  "Terminé": "Completed",
  "points clés": "key points",
  "Commencer la leçon": "Start lesson",
  "Voir le défi": "View challenge",
  "Apprentissage puis défi": "Learning then challenge",
  "Progression sauvegardée": "Progress saved",
  "Plan de la leçon": "Lesson outline",
  "Découvre les mots de la leçon": "Discover the lesson words",
  "Série max (j)": "Max streak (days)",
  "Vous n'avez pas encore contribué.": "You have not contributed yet.",
  "Sécurité & confidentialité": "Security & privacy",
  "Notifications": "Notifications",
  "Compte": "Account",
  "Ouvrir mon profil": "Open my profile",
  "Gérer maintenant": "Manage now",
  "Sections des réglages": "Settings sections",
  "Activer un niveau de protection supplémentaire pour votre compte.": "Enable an extra layer of protection for your account.",
  "Contrôlez les alertes et les rappels d’apprentissage.": "Control alerts and learning reminders.",
  "Dernière sauvegarde": "Last saved",
  "Demande d'assistance": "Support request",
  "Feedback": "Feedback",
  "Aide": "Help",
  "leçons": "lessons",
  "leçon(s)": "lesson(s)",
  "Progression": "Progress",
  "Structure pédagogique": "Learning structure",
  "Clique sur un module puis choisis la leçon à lancer": "Click a module, then choose a lesson to start",
  "Niveau à débloquer": "Level to unlock",
  "Parcours commencés": "Started paths",
  "Bientôt": "Coming soon",
  "Aucune langue ne correspond à votre recherche.": "No language matches your search.",
  "Ma progression": "My progress",
  "Suivez vos progrès et reprenez vos parcours en un coup d’œil.": "Track your progress and resume your learning paths at a glance.",
  "Débutant": "Beginner",
  "Apprenti": "Learner",
  "Intermédiaire": "Intermediate",
  "Avancé": "Advanced",
  "Niveau maximum atteint": "Maximum level reached",
  "Leçons maîtrisées": "Lessons mastered",
  "Commencez à apprendre une langue pour voir votre progression ici": "Start learning a language to see your progress here",
  "Parcours en cours": "Paths in progress",
  "Continuez là où vous vous êtes arrêté.": "Continue where you left off.",
  "Pas encore commencé": "Not started yet",
  "Mémorisation active": "Active memorization",
  "Réviser intelligemment": "Review intelligently",
  "Des rappels adaptés à votre mémoire grâce à la répétition espacée.": "Memory-friendly reminders powered by spaced repetition.",
  "Mode hors-ligne — révision des leçons téléchargées": "Offline mode - review downloaded lessons",
  "À revoir": "To review",
  "Révisions cumulées": "Reviews completed",
  "Cartes maîtrisées": "Cards mastered",
  "Tout est à jour 🚩": "You are all caught up 🚩",
  "Ajoutez vos premiers mots pour démarrer la répétition espacée.": "Add your first words to start spaced repetition.",
  "Cartes à travailler": "Cards to practice",
  "Réviser": "Review",
  "Révision active": "Active review",
  "Rappelle la traduction avant de la révéler.": "Recall the translation before revealing it.",
  "Révéler la réponse": "Reveal answer",
  "Je connais ✓": "I know it ✓",
  "Ajouter un mot à réviser": "Add a word to review",
  "Traduction française": "French translation",
  "Réglages et confidentialité": "Settings and privacy",
  "Centralisez vos préférences, votre sécurité et votre profil.": "Manage your preferences, security, and profile in one place.",
  "Sécurité": "Security",
  "Vos préférences": "Your preferences",
  "Réinitialiser": "Reset",
  "Enregistrer": "Save",
  "Alertes de sécurité": "Security alerts",
  "Recevoir les notifications de sécurité.": "Receive security notifications.",
  "Mode privé": "Private mode",
  "Préférences enregistrées avec succès.": "Preferences saved successfully.",
  "Centre d'aide / Support": "Help & Support",
  "Trouvez une réponse rapidement ou contactez notre équipe.": "Find an answer quickly or contact our team.",
  "Questions fréquentes": "Frequently asked questions",
  "Rechercher dans l’aide...": "Search help...",
  "Aucune réponse trouvée.": "No answer found.",
  "Adresse copiée": "Address copied",
  "Copie impossible": "Unable to copy",
  "Copier l’adresse e-mail": "Copy email address",
  "Ouvrir les réglages": "Open settings",
  "Retour à l’accueil": "Back to home",
  "Profil": "Profile",
  "Leçons": "Lessons",
  "Langues": "Languages",
  "Erreur lors de l'upload :": "Upload error:",
  "En attente": "Pending",
  "Validées": "Approved",
  "Validé": "Approved",
  "Refusé": "Rejected",
  "Administration": "Administration",
  "jours série": "streak days",
  "Impossible de sauvegarder la progression : requête invalide.": "Unable to save progress: invalid request.",
  "Erreur lors de la sauvegarde de la progression. Réessayez plus tard.": "Error saving progress. Please try again later.",
  "Vous devez être connecté pour sauvegarder la progression.": "You must be signed in to save your progress.",
  "Encore": "Still",
  "leçons totales": "total lessons",
  "langue(s)": "language(s)",
  "carte(s) prête(s) aujourd’hui": "card(s) ready today",
  "affichée(s)": "shown",
  "À travailler": "To practice",
  "niveaux": "levels",
  "acquises": "learned",
  "Curriculum": "Curriculum",
  "Parcours d'apprentissage": "Learning paths",
  "Choisissez votre prochaine langue": "Choose your next language",
  "Progressez à votre rythme avec des leçons pensées pour comprendre, pratiquer et retenir.": "Learn at your own pace with lessons designed to understand, practice, and retain.",
  "Langues disponibles": "Available languages",
  "Parcours actifs": "Active paths",
  "XP total": "Total XP",
  "Rechercher une langue ou un pays...": "Search for a language or country...",
  "Effacer la recherche": "Clear search",
  "Pays :": "Country:",
  "Toutes": "All",
  "Tous les parcours": "All learning paths",
  "Erreur lors de l'envoi :": "Error sending:",
  "leçons réparties dans": "lessons distributed in",
  "modules": "modules",
  "résultat(s)": "result(s)",
  "Parcours": "Path",
  "Exercice global": "Global exercise",
  "Erreur de chargement :": "Loading error:",
  "Leçon": "Lesson",
  "Quiz": "Quiz",
  "objectifs": "objectives",
  "phrases": "phrases",
  "Environ": "About",
  "parties": "sections",
  "Sections de la leçon": "Lesson sections",
  "Apprentissage / Vocabulaire": "Learning / Vocabulary",
  "Objectifs": "Objectives",
  "Vocabulaire": "Vocabulary",
  "Phrases": "Phrases",
  "Phonétique": "Phonetics",
  "Grammaire": "Grammar",
  "Dialogue": "Dialogue",
  "Culture": "Culture",
  "Exercices": "Exercises",
  "Sources": "Sources",

  "Retour au curriculum": "Back to curriculum",
  "Les points de grammaire": "Grammar points",
  "Espace d’apprentissage": "Learning space",
  "Dialogue de la leçon": "Lesson dialogue",
  "Masquer la traduction": "Hide translation",
  "Voir la traduction": "Show translation",
  "Examen de la leçon": "Lesson review",
  "mots": "words",
  "cartes": "cards",
  "Écouter": "Listen",
  "Écouter les sons clés": "Listen to key sounds",
  "défis": "challenges",
  "Objectif maîtrisé": "Goal mastered",
  "Marquer comme acquis": "Mark as learned",
  "Réponds à chaque question sans voir la correction. La note finale sera calculée définitivement.": "Answer each question without viewing the correction. Your final score will be calculated at the end.",
  "Paramètres": "Settings",
  "Informations du compte": "Account Information",
  "Modifiez votre nom et votre mot de passe.": "Modify your name and password.",
  "Nom utilisateur": "Username",
  "Mot de passe actuel": "Current password",
  "Confirmer le nouveau": "Confirm new password",
  "Thème sombre": "Dark theme",
  "Thème clair": "Light theme",
  "Thème": "Theme",
  "Basculer": "Toggle",
  "Aucune URL de photo renvoyée.": "No photo URL returned.",
  "Se déconnecter": "Sign out",
  "currentRank": "Current rank",
  "still": "Still",
  "totalLessons": "total lessons",
  "to": "to",
  "maxLevelReached": "Maximum level reached",
  "beginner": "Beginner",
  "learner": "Learner",
  "intermediate": "Intermediate",
  "advanced": "Advanced",
  "loadingProgress": "Loading progress...",
  "noProgressYet": "No progress yet",
  "startLearningToSeeProgress": "Start learning a language to see your progress here",
  "progressionByLanguage": "Progression by language",
  "lessonsMastered": "Lessons mastered",
  "maxStreakDays": "Max streak (days)",
  "languagesActive": "active languages",
};

Object.assign(translations.en, sharedUiTranslations);

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window === "undefined") return "en";
    const saved = window.localStorage.getItem("maa-kweli-language");
    return saved === "fr" ? "fr" : "en";
  });

  useEffect(() => {
    window.localStorage.setItem("maa-kweli-language", language);
    document.documentElement.lang = language;
  }, [language]);

  const value = {
    language,
    setLanguage,
    toggleLanguage: () => setLanguage((current) => current === "fr" ? "en" : "fr"),
    t: (key, ...args) => {
      const value = translations[language][key] ?? translations.fr[key] ?? key;
      return typeof value === "function" ? value(...args) : value;
    },
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}